### ISSUE TITLE
Fonts not working

### ISSUE THREAD

**Issue by LPB8479** [LPB8479/idm221-nas367#1]
Hey @philsinatra, can you help me figure out why my fonts are not working?
Thanks!

https://github.com/LPB8479/idm221-nas367/blob/main/deploy/css/styles.css

**Comment by philsinatra** [comment]
Are you running your project from the _deploy_ folder? Your path is relative to your CSS file.

https://github.com/LPB8479/idm221-nas367/blob/217431fd4704d3b86ad421848b3b019915d2ae1b/deploy/css/styles.css#L3

This line says, "go up one directory, then into the `fonts` directory, and load the TTF file. That path does not match your directory structure.

**Comment by LPB8479** [comment]
I believe I fixed that (now `../../fonts...`), but it's still defaulting to Times New Roman. Could it have something to do with how I'm defining the font family, either with how I'm defining the family overall at the top of the file or for the individual elements at the bottom?
![image](https://github.com/LPB8479/idm221-nas367/assets/76528559/c0e5b042-f17b-4550-8b11-ea5e57d71137)

**Comment by philsinatra** [comment]
Based on your directory structure on GitHub, you need a copy of your 'fonts' directory in the 'deploy' directory. Then, your original path should work.

**Comment by LPB8479** [comment]
For some reason, that still is not fixing it. I think it might be best to wait until class on Thursday and we can fix it in person during studio time.

**Comment by philsinatra** [comment]
## Fixing the `font-family` declaration

Inside the `@font-face` declaration, the `font-family` property value should only have one value. Think of it like the name of the font you're declaring.

```diff
@font-face {
- font-family: "Open Sans", sans-serif;
+ font-family: "Open Sans";
  src: url(../../deploy/fonts/OpenSans-VariableFont.ttf);
}
```

When you use the custom font, you can include it as one of the options in the font stack.

```css
p {
  font-family: "Open Sans", Helvetica, sans-serif;
}
```

## Adjusting the path

You can simplify the path to your font file. Currently, you spec:

> Go up two directories, then go into the `deploy` directory, then into the `fonts` directory.

The contents of the `deploy` folder should be the compiled code users will access on a live server. Ideally, all of the links in your code should be relative between files in the `deploy` folder.

```diff
@font-face {
  font-family: "Open Sans", sans-serif;
- src: url(../../deploy/fonts/OpenSans-VariableFont.ttf);
+ src: url(../fonts/OpenSans-VariableFont.ttf);
}
```

## DRY

Try not to repeat identical declarations for multiple selectors.

https://github.com/LPB8479/idm221-nas367/blob/050489b37bbfb0d1589754799407bea919a73be5/dev/scss/base/_typography.scss#L11-L40

You can apply identical styles to multiple elements by declaring multiple selectors, separated by commas:

```css
p, h1, h2, h3 { font-family: "Open Sans", sans-serif; }
```

If you want everything to use Open Sans, declare it as the font family for the `body`. All other elements will automatically inherit this value; you don't have to specify it again.

```css
body { font-family: "Open Sans", sans-serif; }
```

**Comment by LPB8479** [comment]
Got it all working! Thanks!
